import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Badge, Card, CardBody, CardHeader, Divider, Heading, SimpleGrid, Stack, Stat, StatHelpText, StatLabel, StatNumber, Text, } from '@chakra-ui/react';
import { Suspense, lazy } from 'react';
import { Line, LineChart, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, BarChart, Bar, } from 'recharts';
const ReviewDiff = lazy(() => import('@components/ReviewDiff').then((module) => ({ default: module.ReviewDiff })));
import { useListReviews, useReviewSummary } from '@features/reviews/api';
export const DashboardPage = () => {
    const { data: reviewsData, isLoading: loadingReviews } = useListReviews();
    const { data: summary, isLoading: loadingSummary } = useReviewSummary();
    return (_jsxs(Stack, { spacing: 8, children: [_jsx(AnalyticsHeader, { summaryLoading: loadingSummary, summary: summary }), _jsx(AnalyticsCharts, { summaryLoading: loadingSummary, summary: summary }), _jsx(RecentReviews, { loading: loadingReviews, reviews: reviewsData?.items ?? [] })] }));
};
const AnalyticsHeader = ({ summaryLoading, summary }) => (_jsxs(SimpleGrid, { columns: { base: 1, md: 3 }, spacing: 6, children: [_jsx(Card, { children: _jsx(CardBody, { children: _jsxs(Stat, { children: [_jsx(StatLabel, { children: "Average score" }), _jsx(StatNumber, { children: summaryLoading ? '…' : summary?.avgScore != null ? summary.avgScore.toFixed(2) : '—' }), _jsx(StatHelpText, { children: "Across completed reviews" })] }) }) }), _jsx(Card, { children: _jsx(CardBody, { children: _jsxs(Stat, { children: [_jsx(StatLabel, { children: "In queue" }), _jsx(StatNumber, { children: summaryLoading ? '…' : summary?.pending ?? 0 }), _jsx(StatHelpText, { children: "Submissions awaiting processing" })] }) }) }), _jsx(Card, { children: _jsx(CardBody, { children: _jsxs(Stat, { children: [_jsx(StatLabel, { children: "Average turnaround" }), _jsx(StatNumber, { children: summaryLoading
                                ? '…'
                                : summary?.turnaroundHours
                                    ? `${summary.turnaroundHours.toFixed(1)} h`
                                    : '—' }), _jsx(StatHelpText, { children: "From submission to final review" })] }) }) })] }));
const AnalyticsCharts = ({ summaryLoading, summary }) => {
    if (summaryLoading) {
        return null;
    }
    return (_jsxs(SimpleGrid, { columns: { base: 1, md: 2 }, spacing: 6, children: [_jsxs(Card, { children: [_jsx(CardHeader, { children: _jsx(Heading, { size: "md", children: "Throughput (last 7 days)" }) }), _jsx(CardBody, { height: "250px", children: _jsx(ResponsiveContainer, { width: "100%", height: "100%", children: _jsxs(LineChart, { data: summary?.throughput.daily ?? [], children: [_jsx(CartesianGrid, { strokeDasharray: "3 3" }), _jsx(XAxis, { dataKey: "date" }), _jsx(YAxis, { allowDecimals: false }), _jsx(Tooltip, {}), _jsx(Line, { type: "monotone", dataKey: "count", stroke: "#3182ce", strokeWidth: 3 })] }) }) })] }), _jsxs(Card, { children: [_jsx(CardHeader, { children: _jsx(Heading, { size: "md", children: "Most frequent issue categories" }) }), _jsx(CardBody, { height: "250px", children: _jsx(ResponsiveContainer, { width: "100%", height: "100%", children: _jsxs(BarChart, { data: summary?.commonIssues ?? [], children: [_jsx(CartesianGrid, { strokeDasharray: "3 3" }), _jsx(XAxis, { dataKey: "category" }), _jsx(YAxis, { allowDecimals: false }), _jsx(Tooltip, {}), _jsx(Bar, { dataKey: "count", fill: "#805AD5", radius: [6, 6, 0, 0] })] }) }) })] })] }));
};
const RecentReviews = ({ loading, reviews }) => (_jsxs(Card, { children: [_jsxs(CardHeader, { children: [_jsx(Heading, { size: "md", children: "Recent reviews" }), _jsx(Text, { fontSize: "sm", color: "gray.500", children: "See the latest submissions and compare them with the suggested AI improvements." })] }), _jsxs(CardBody, { children: [loading && _jsx(Text, { children: "Loading reviews\u2026" }), !loading && !reviews.length && _jsx(Text, { children: "No reviews found yet." }), _jsx(Stack, { spacing: 8, divider: _jsx(Divider, {}), children: reviews.map(({ submission, review }) => (_jsxs(Stack, { spacing: 3, children: [_jsxs(Heading, { size: "sm", children: [submission.language.toUpperCase(), " \u2022 #", submission.id.slice(-6)] }), _jsxs(Text, { fontSize: "sm", color: "gray.500", children: ["Status: ", submission.status] }), review?.summary && _jsx(Text, { children: review.summary }), review?.issues?.length ? (_jsx(Stack, { spacing: 2, children: review.issues.map((issue, index) => (_jsxs(Badge, { colorScheme: "orange", children: [issue.severity.toUpperCase(), " \u2022 ", issue.category, ": ", issue.description] }, `${submission.id}-issue-${index}`))) })) : (_jsx(Text, { fontSize: "sm", color: "gray.500", children: "No critical issues highlighted." })), _jsx(Suspense, { fallback: _jsx(Text, { fontSize: "sm", color: "gray.400", children: "Loading diff\u2026" }), children: _jsx(ReviewDiff, { original: submission.content, improved: review?.improved_code, language: submission.language }) })] }, submission.id))) })] })] }));
