import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import ReactDOM from 'react-dom/client';
import { ChakraProvider, ColorModeScript } from '@chakra-ui/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { BrowserRouter } from 'react-router-dom';
import App from './App';
import theme from './theme';
const queryClient = new QueryClient();
ReactDOM.createRoot(document.getElementById('root')).render(_jsxs(React.StrictMode, { children: [_jsx(ColorModeScript, { initialColorMode: "light" }), _jsx(QueryClientProvider, { client: queryClient, children: _jsx(ChakraProvider, { theme: theme, children: _jsx(BrowserRouter, { children: _jsx(App, {}) }) }) })] }));
